### ISSUE TITLE
Add Ruby plugin logo

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-ruby#1]
Logo from Wikipedia: https://en.wikipedia.org/wiki/Ruby_(programming_language)#/media/File:Ruby_logo.svg
![изображение](https://user-images.githubusercontent.com/16825982/139643265-e03a9b31-487c-48ee-a505-d9101e46473c.png)

**Comment by VISTALL** [comment]
There some bug in svg render. Created issue https://github.com/blackears/svgSalamander/issues/83
